kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-users
subjects:
  - kind: ServiceAccount
    name: example-user01
    namespace: example
roleRef:
  kind: ClusterRole
  name: view 
  apiGroup: rbac.authorization.k8s.io