kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-admin
subjects:
  - kind: ServiceAccount 
    name: example-user01
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io