apiVersion: v1
kind: Service
metadata:
  labels:
    run: node-todo
  name: node-todo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: node-todo
  sessionAffinity: None
  type: LoadBalancer
