kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewonly-users
subjects:
  - kind: user
    name: appdev
roleRef:
  kind: ClusterRole
  name: view 
  apiGroup: rbac.authorization.k8s.io