apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-volume
  labels:
    nfs: "primary"
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /exports
    server: 10.100.200.99
    readOnly: false
  