# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: nfs
  labels:
    app: nfs-server
spec:
  ports:
  - port: 2049
    name: nfs
  - port: 20048
    name: mountd
  - port: 111
    name: rpcbind
  clusterIP: 10.100.200.99
  selector:
    app: nfs-server